/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Allows side-effect imports of global.css (Tailwind directives) under tsc --noEmit
declare module "*.css";
